[package]
name = "day-four"
version = "0.1.0"
authors = ["Jan Vandepitte <Jan.Vandepitte@mediahuis.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
